### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ryo-suemura** [ryo-suemura/furima-29839#11]
# URL
https://furima-29893.herokuapp.com/

# Basic認証のIDとパスワード
id：minimal  
password：0508

# 出品者(出品商品はtest3、test4)
mail：a@a.com
password：aaaaaa1

# 購入者
mail：b@b.com
password：bbbbbb1

# クレジットカード
番号：4242424242424242
期限：02/22
コード：123

**Comment by mutorisa** [comment]
末村さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by ryo-suemura** [comment]
有り難うございました！
